name: lnpdb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.20
  - numpy=1.26.4
  - pandas=2.2.3
  - matplotlib=3.9.2
  - mdanalysis=2.7.0
  - tqdm=4.67.0
  - joblib=1.4.2
  - seaborn=0.13.2
  - scipy=1.13.1
  - pip
  - pip:
      - jupyter